# Website settings
baseurl: "/"
url: "http://www.gruntwork.io"
name: "Gruntwork"
description: "Get up and running on AWS with DevOps best practices and world-class infrastructure in about 2 weeks. You focus on your product. We'll take care of the grunt work."
full_company_name: "Gruntwork, LLC"
thumbnail_path: "logo/gruntwork-logo-standalone.png"

# Jekyll build settings
# paginate: 10
# paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
