# Website settings
baseurl: "/"
url: "http://www.gruntwork.io"
name: "Gruntwork"
description: "Description TODO"
full_company_name: "Gruntwork, LLC"

# Contact settings
contact:
  email: "info@gruntwork.io"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
