AWS:
  key: standard_subscription
  stripeProductId: prod_KZH5PYGPzdh5nu
ProSupport:
  key: pro_support
  stripeProductId: prod_KZHA5WMpiNsnOs
RefArch:
  key: setup_deployment
  stripeProductId: prod_KZHHUK5LUuYRFl
CIS:
  key: setup_compliance
  stripeProductId: prod_KZH9VxdizHvbqI
Users:
  key: standard_users
  stripeProductId: prod_KZH7Hb6FqIPOcl
