- title: A Crash Course on Terraform
  description: Learn how to manage infrastructure as code using Terraform through a series of live coding exercises.
  url: "https://gruntwork.teachable.com/p/terraform"
  author: Josh Padnick
  author_thumbnail: /assets/img/josh-thumbnail.png
  course_thumbnail: /assets/img/terraform-logo-training.png
  videos: 30
  duration: 92 minutes
  bg_color: purple

- title: A Crash Course on Docker &amp; Packer
  description: Learn how to package your code using Packer and Docker into immutable images that run exactly the same way in all environments.
  url: "https://gruntwork.teachable.com/p/a-crash-course-on-docker-packer"
  author: Yevgeniy Brikman
  author_thumbnail: /assets/img/yevegeniy-thumbnail.png
  course_thumbnail: /assets/img/docker-packer-training.png
  videos: 40
  duration: 95 minutes
  bg_color: orange

- title: Reference Architecture Walkthrough
  description: Learn everything you need to know to get started with the Gruntwork Reference Architecture.
  url: "https://gruntwork.teachable.com/p/reference-architecture-walkthrough"
  author: Yevgeniy Brikman
  author_thumbnail: /assets/img/yevegeniy-thumbnail.png
  course_thumbnail: /assets/img/grunty-training.png
  videos: 41
  duration: 100 minutes
  bg_color: blue
