- title: Reusable, composable, battle-tested Terraform modules
  url: "https://www.ybrikman.com/writing/2017/10/13/reusable-composable-battle-tested-terraform-modules/"
  image: /assets/img/training-resources/training-terraform-modules.png
  description: |
    A talk from HashiConf 2017 where Jim introduces the work we've been doing at Gruntwork with Terraform Modules.
    Learn how modules work, how to design modules so they are highly configurable and reusable, and how to write
    automated tests for your Terraform code. Most importanly, see how you can use modules to build your entire tech
    stack on top of proven, battle-tested infrastructure code—in minutes.

- title: Terraform Up &amp; Running
  url: "https://www.terraformupandrunning.com"
  image: /assets/img/training-resources/training-terraform-up-and-running.png
  description: |
    This book is the fastest way to get up and running with Terraform. Rated 4.5 stars on Amazon.

- title: The Comprehensive Guide to Terraform
  url: "https://blog.gruntwork.io/a-comprehensive-guide-to-terraform-b3d32832baca"
  image: /assets/img/training-resources/training-comprehensive-guide-terraform.png
  description: |
    Our blog post series on how to use Terraform. Over 100,000 views.

- title: A Comprehensive Guide to Building a Scalable Web App on Amazon Web Services
  url: "https://www.airpair.com/aws/posts/building-a-scalable-web-app-on-amazon-web-services-p1"
  image: /assets/img/training-resources/training-a-comprehensive-guide.png
  description: |
    A definitive guide on how to think about building apps on AWS. Received over 500 upvotes on Hacker News.

- title: "Running microservices on AWS using Docker, Terraform, and ECS"
  url: "https://www.ybrikman.com/writing/2016/03/31/infrastructure-as-code-microservices-aws-docker-terraform-ecs/"
  image: /assets/img/training-resources/training-infrastructure-as-code.png
  description: |
    A talk from DevOps Italia 2016 that shows how to use Terraform, Docker, and Amazon's EC2 Container Service to run
    microservices in AWS.

- title: "Choosing the Right Framework for Running Docker Containers in Production"
  url: "https://joshpadnick.com/2015/09/01/my-talk-on-choosing-the-right-framework-for-running-docker-containers-in-production/"
  image: /assets/img/training-resources/training-choosing-framework-docker.png
  description: |
    A talk from Iterate.PHX on choosing the right framework for running docker containers in production. Goes over the
    trade-offs between Amazon ECS, Docker Swarm, CoreOS Fleet, Deis, Flynn, Mesos, and Kubernetes.
